# Generated by Django 5.0.9 on 2024-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmaster',
            name='session_year',
            field=models.CharField(max_length=20),
        ),
    ]
