# Generated by Django 5.0.9 on 2024-11-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0001_initial'),
        ('SessionApp', '0002_alter_sessionmaster_session_year'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.classmaster')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionApp.sessionmaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
