# Generated by Django 5.0.9 on 2024-11-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0001_initial'),
        ('SessionApp', '0003_studentsession'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsession',
            unique_together={('session', 'class_id', 'student')},
        ),
    ]
