# Generated by Django 5.0.9 on 2024-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0004_alter_studentsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmaster',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
    ]
