# Generated by Django 5.0.9 on 2024-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages='First Name is required', max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='1', max_length=20)),
                ('email', models.EmailField(error_messages='Email is required', max_length=250, unique=True)),
                ('parents_mobile', models.PositiveBigIntegerField(error_messages='Mobile is required', unique=True)),
                ('aadhar_number', models.CharField(max_length=18)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('admission_date', models.DateField(error_messages='Admission date is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
